# Default values for helm-template.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  nodePort: 30000 # if type: NodePort
  loadBalancerIP: 192.168.0.100 # if type: LoadBalancer

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  emptyDir:  false # emptyDir differs from hostPath since emptyDir will be deleted after pod deletion
  hostPath: true # if you use hostPath, you should fill nodeSelector field
  hostPathDirectory: /opt/blablabla # applicable if hostPath: true, ignored in other cases
  storageClass: blablabla # ignored if emptyDir: true or hostPath: true
  size: 8Gi # ignored if emptyDir: true or hostPath: true
  containerDirectory: /usr/share/nginx/html # container directory which should persist

env:
 - name: "USERNAME"
   value: ""
 - name: "PASSWORD"
   value: ""
